# Window
window_padding_width 12
# remove title bar and window borders
hide_window_decorations yes
# allow runtime opacity changes via remote control
dynamic_background_opacity yes
# background_opacity 0.90
# background_blur 32

# Cursor
cursor_shape block
cursor_blink_interval 1
# number of trail cursors to render
cursor_trail 3
# fade start and end times in seconds
cursor_trail_decay 0.1 0.4
