# Performance (minimize latency, higher energy usage)
# no buffering of input, send immediately
input_delay 0
# near-zero delay between screen repaints (ms)
repaint_delay 2
# don't wait for vsync, prioritize responsiveness
sync_to_monitor no
