# Plugin manager
set -g @plugin "tmux-plugins/tpm"

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "A-h"
set -g @vim_navigator_mapping_right "A-l"
set -g @vim_navigator_mapping_up "A-k"
set -g @vim_navigator_mapping_down "A-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Dynamic window titles
# set -g @plugin 'ofirgall/tmux-window-name'

# Rose Pine Theme
set -g @rose_pine_variant 'moon'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_directory 'on'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_only_windows 'off'
set -g @rose_pine_status_left_append_section '  '  # Add spacing after session name
set -g @rose_pine_status_right_prepend_section '  '  # Add spacing before right section
set -g @rose_pine_field_separator ' | '  # Separator between fields in right section
set -g @rose_pine_window_separator ' -> '
set -g @rose_pine_window_status_separator "  │  "
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @plugin 'rose-pine/tmux'
