[opener]
imgopen = [{ run = 'zen-browser "$@"', orphan = true, for = "unix" }]
edit = [{ run = "$EDITOR \"$@\"", block = true, for = "unix" }]
fallback = [{ run = "xdg-open \"$@\"", orphan = true, for = "unix" }]

[open]
rules = [
	{ mime = "image/*", use = "imgopen" },
	{ mime = "text/*", use = "edit" },
	{ name = "*", use = "fallback" },
	{ mime = "*", use = "fallback" },
]

[mgr]
show_hidden = true
