[colors]
background = '#1a1111'
foreground = '#f1dedd'

cursor_bg = '#ffb3ae'
cursor_fg = '#1a1111'
cursor_border = '#ffb3ae'

selection_bg = '#733330'
selection_fg = '#f1dedd'

ansi = ['#1a1111', '#ff7372', '#9aff7f', '#ffe472', '#f29b95', '#763531', '#ffb3ae', '#fff0ef']
brights = ['#484040', '#ffa09f', '#b8ffa5', '#ffeda5', '#ffbeba', '#ffc9c6', '#ffdcda', '#fff8f8']
