[colors]
background = '#171217'
foreground = '#eadfe7'

cursor_bg = '#e9b5ef'
cursor_fg = '#171217'
cursor_border = '#e9b5ef'

selection_bg = '#603768'
selection_fg = '#eadfe7'

ansi = ['#171217', '#ff7285', '#77ef97', '#ffdd72', '#dca0e3', '#693d6e', '#e9b5ef', '#f9ebfa']
brights = ['#9a8f9b', '#ff9fac', '#a5ffbd', '#ffe9a5', '#f9caff', '#fad3ff', '#fce3ff', '#fef8ff']
